### This Notebook performs ETL on data for an Insurance Project

In [ ]:
# Import Libraries
import pandas as pd

In [ ]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Load Companies Dataset
file_loc = '/content/drive/MyDrive/Datasets/Companies Ins.Data.xlsx'

In [ ]:
# Load Customers Dataset
file_loc_csv = '/content/drive/MyDrive/Datasets/Insurance.csv'

In [ ]:
# Load customers table
customers = pd.read_csv(file_loc_csv)

# Load tables/sheet from the Dataset
corporate_clients = pd.read_excel(file_loc, sheet_name = 'Corporate Clients')
covered_employees = pd.read_excel(file_loc, sheet_name = 'Covered Employees')
claims = pd.read_excel(file_loc, sheet_name = 'Claims')
policy_table = pd.read_excel(file_loc, sheet_name = 'Policy Table')
premium_payments = pd.read_excel(file_loc, sheet_name = 'Premium Payments')
branch_table = pd.read_excel(file_loc, sheet_name = 'Branch Table')
claim_workflow = pd.read_excel(file_loc, sheet_name = 'Claim Workflow')
beneficiaries = pd.read_excel(file_loc, sheet_name = 'Beneficiaries')
risk_scores = pd.read_excel(file_loc, sheet_name = 'Risk Scores')

In [ ]:
# Preview Customers table
customers.head()

,Customer_ID,Full_Name,Age,Gender,Occupation,Grade_Level,Monthly_Income_GHS,Region,Product_Applied,Smoker,...,Premium_GHS,Payment_Method,Application_Date,Policy_Status,Tenure_Months,Payment_Behavior,Claim_Frequency,Claim_Severity,Agent_ID,Agent_Name
0,C0750001,Rachel Richardson,27,Female,Driver,Junior,2702,Takoradi,Mekakrawa,No,...,478.03,MoMo,2024-12-19,Cancelled,12,Frequently Late,0,NaN,AG013,Linda Nyarko
1,C0750002,Cody Macias,64,Male,Data Analyst,Junior,6314,Koforidua,Mekakrawa,Yes,...,417.29,MoMo,2024-10-23,Active,14,Occasionally Late,2,High,AG023,Benjamin Nyarko
2,C0750003,Joshua Brown,61,Male,Construction Worker,Mid,3048,Cape Coast,Prudential Travel Insurance Plan,Yes,...,945.59,Payroll Deduction,2025-11-05,Renewed,1,Consistent,2,High,AG017,Josephine Arthur
3,C0750004,Loretta Cross,48,Male,Software Engineer,Junior,7811,Kumasi,Mekakrawa,No,...,180.75,Bank Transfer,2024-05-12,Active,19,Occasionally Late,1,Low,AG011,Emmanuel Sarkodie
4,C0750005,Joshua Gonzalez,50,Male,Software Engineer,Senior,23078,Koforidua,Mekakrawa,Yes,...,670.93,Bank Transfer,2025-02-10,Pending Renewal,10,Consistent,1,Medium,AG023,Benjamin Nyarko

In [ ]:
# Preview tables
corporate_clients.head()

,Corporate_ID,Company_Name,Branch_ID,Industry,Region,Number_of_Staff,Insurance_Product,Premium_Per_Staff_GHS,Insurance_Purpose,Application_Date
0,CORP001,MTN Ghana,BR001,Telecommunications,Accra,1800,Group Welfare Plan,248,HR Benefits,2025-11-15
1,CORP002,MTN Ghana,BR002,Telecommunications,Kumasi,250,Group Welfare Plan,254,Employee Welfare,2024-11-08
2,CORP003,MTN Ghana,BR003,Telecommunications,Takoradi,120,Group Funeral Insurance Plan,219,Talent Retention,2024-05-24
3,CORP004,MTN Ghana,BR004,Telecommunications,Tamale,80,Group Welfare Plan,232,Employee Welfare,2024-11-06
4,CORP005,MTN Ghana,BR005,Telecommunications,Ho,35,Group Life Insurance Plan,226,Employee Welfare,2024-03-06

In [ ]:
# Preview table
covered_employees.head()

,Employee_ID,Corporate_ID,Employee_Name,Occupation,Grade_Level,Monthly_Salary_GHS,Age,Gender,Dependents,Smoker
0,EMP00001,CORP001,April Perez,Network Engineer,Mid,12000,43,Male,2,Yes
1,EMP00002,CORP001,Jonathan Morris,Software Engineer,Junior,8500,40,Female,4,No
2,EMP00003,CORP001,Kathryn Cook,Network Engineer,Junior,7500,40,Male,4,No
3,EMP00004,CORP001,Christopher Johnson,Software Engineer,Mid,13000,51,Female,0,Yes
4,EMP00005,CORP001,Kenneth Thompson,Software Engineer,Junior,8500,58,Female,0,No

In [ ]:
# Preview table
claims.head()

,Claim_ID,Employee_ID,Corporate_ID,Claim_Type,Claim_Amount_GHS,Claim_Status,Claim_Date
0,CLM00001,EMP01950,CORP069,Funeral Benefit,15040,Approved,2024-09-24
1,CLM00002,EMP00184,CORP007,Dental,7155,Rejected,2025-12-08
2,CLM00003,EMP00706,CORP027,Funeral Benefit,15572,Pending,2025-03-07
3,CLM00004,EMP01925,CORP069,Hospitalization,44381,Approved,2024-05-12
4,CLM00005,EMP01390,CORP049,Emergency Care,14988,Pending,2024-07-28

In [ ]:
# Preview table
policy_table.head()

,Policy_ID,Corporate_ID,Insurance_Product,Policy_Start_Date,Policy_End_Date,Policy_Status
0,POL0001,CORP001,Group Welfare Plan,2025-11-15,2026-11-15,Renewed
1,POL0002,CORP002,Group Welfare Plan,2024-11-08,2025-11-08,Renewed
2,POL0003,CORP003,Group Funeral Insurance Plan,2024-05-24,2025-05-24,Pending Renewal
3,POL0004,CORP004,Group Welfare Plan,2024-11-06,2025-11-06,Renewed
4,POL0005,CORP005,Group Life Insurance Plan,2024-03-06,2025-03-06,Pending Renewal

In [ ]:
# Preview table
premium_payments.head()

,Payment_ID,Corporate_ID,Payment_Date,Amount_GHS,Payment_Status,Payment_Method
0,PAY00011,CORP001,2025-12-15,37200,Pending,Payroll Deduction
1,PAY00012,CORP001,2026-01-15,37200,Paid,Bank Transfer
2,PAY00013,CORP001,2026-02-15,37200,Paid,Payroll Deduction
3,PAY00014,CORP001,2026-03-15,37200,Paid,Bank Transfer
4,PAY00015,CORP001,2026-04-15,37200,Paid,Bank Transfer

In [ ]:
# Preview table
branch_table.head()

  Branch_ID Company_Name    Region
0     BR001    MTN Ghana     Accra
1     BR002    MTN Ghana    Kumasi
2     BR003    MTN Ghana  Takoradi
3     BR004    MTN Ghana    Tamale
4     BR005    MTN Ghana        Ho

In [ ]:
# Preview table
claim_workflow.head()

,Workflow_ID,Claim_ID,Submitted_Date,Reviewed_Date,Approved_By,Payout_Date
0,WF00001,CLM00001,2025-01-23,2025-01-27,Abena Ofori,NaN
1,WF00002,CLM00002,2024-06-12,2024-06-24,Michael Owusu,2024-07-04
2,WF00003,CLM00003,2025-10-15,2025-10-19,Daniel Asare,NaN
3,WF00004,CLM00004,2024-07-25,2024-07-28,Abena Ofori,NaN
4,WF00005,CLM00005,2024-09-16,2024-09-20,Kwame Mensah,2024-09-24

In [ ]:
# Preview table
beneficiaries.head()

,Beneficiary_ID,Employee_ID,Beneficiary_Name,Relationship,Allocation_Percentage
0,BEN00001,EMP00001,April Perez Family,Spouse,100
1,BEN00002,EMP00002,Jonathan Morris Family,Sibling,100
2,BEN00003,EMP00003,Kathryn Cook Family,Parent,100
3,BEN00004,EMP00004,Christopher Johnson Family,Sibling,100
4,BEN00005,EMP00005,Kenneth Thompson Family,Sibling,100

In [ ]:
# Preview table
risk_scores.head()

    Risk_ID Employee_ID
0  RSK00001    EMP00001
1  RSK00002    EMP00002
2  RSK00003    EMP00003
3  RSK00004    EMP00004
4  RSK00005    EMP00005

# ETL: Retail Insurance

In [ ]:
# Preview customers
customers

,Customer_ID,Full_Name,Age,Gender,Occupation,Grade_Level,Monthly_Income_GHS,Region,Product_Applied,Smoker,...,Premium_GHS,Payment_Method,Application_Date,Policy_Status,Tenure_Months,Payment_Behavior,Claim_Frequency,Claim_Severity,Agent_ID,Agent_Name
0,C0750001,Rachel Richardson,27,Female,Driver,Junior,2702,Takoradi,Mekakrawa,No,...,478.03,MoMo,2024-12-19,Cancelled,12,Frequently Late,0,NaN,AG013,Linda Nyarko
1,C0750002,Cody Macias,64,Male,Data Analyst,Junior,6314,Koforidua,Mekakrawa,Yes,...,417.29,MoMo,2024-10-23,Active,14,Occasionally Late,2,High,AG023,Benjamin Nyarko
2,C0750003,Joshua Brown,61,Male,Construction Worker,Mid,3048,Cape Coast,Prudential Travel Insurance Plan,Yes,...,945.59,Payroll Deduction,2025-11-05,Renewed,1,Consistent,2,High,AG017,Josephine Arthur
3,C0750004,Loretta Cross,48,Male,Software Engineer,Junior,7811,Kumasi,Mekakrawa,No,...,180.75,Bank Transfer,2024-05-12,Active,19,Occasionally Late,1,Low,AG011,Emmanuel Sarkodie
4,C0750005,Joshua Gonzalez,50,Male,Software Engineer,Senior,23078,Koforidua,Mekakrawa,Yes,...,670.93,Bank Transfer,2025-02-10,Pending Renewal,10,Consistent,1,Medium,AG023,Benjamin Nyarko
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
949995,C0249996,Nicole Perez,62,Female,Software Engineer,Junior,8809,Takoradi,Dignity Farewell Plan,Yes,...,201.52,MoMo,2024-02-28,Lapsed,22,Frequently Late,1,Low,AG013,Linda Nyarko
949996,C0249997,Angela Johnson,26,Male,Driver,Senior,4575,Sunyani,Prudential Travel Insurance Plan,Yes,...,678.61,MoMo,2025-09-11,Cancelled,3,Frequently Late,0,NaN,AG022,Collins Addae
949997,C0249998,Stephen Smith,46,Male,Accountant,Junior,4604,Kumasi,Pru Wealth Plan,No,...,283.88,Payroll Deduction,2024-06-01,Active,18,Consistent,0,NaN,AG009,Francis Annor
949998,C0249999,Alexa West,63,Female,Accountant,Senior,10315,Kumasi,Dignity Farewell Plan,Yes,...,534.50,Bank Transfer,2024-09-24,Lapsed,15,Occasionally Late,2,Medium,AG011,Emmanuel Sarkodie
949999,C0250000,Krystal Newman,25,Female,Software Engineer,Junior,7625,Koforidua,Mekakrawa,No,...,317.83,Payroll Deduction,2024-12-31,Active,12,Consistent,0,NaN,AG023,Benjamin Nyarko

In [ ]:
customers.describe()

,Age,Monthly_Income_GHS,BMI,Dependents,Premium_GHS,Tenure_Months,Claim_Frequency
count,950000.00000,950000.000000,950000.000000,950000.000000,950000.000000,950000.000000,950000.000000
mean,43.04348,8414.998260,27.257548,2.512400,475.238569,11.478800,0.658560
std,12.95214,5599.778852,5.347058,1.706801,255.654276,6.907214,0.926553
min,21.00000,1801.000000,18.000000,0.000000,60.890000,0.000000,0.000000
25%,32.00000,4162.000000,22.600000,1.000000,272.027500,5.000000,0.000000
50%,43.00000,7276.000000,27.300000,3.000000,426.810000,12.000000,0.000000
75%,54.00000,11059.000000,31.900000,4.000000,641.320000,17.000000,1.000000
max,65.00000,39982.000000,36.500000,5.000000,1247.190000,23.000000,4.000000

In [ ]:
customers.shape

(950000, 23)

In [ ]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950000 entries, 0 to 949999
Data columns (total 23 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Customer_ID         950000 non-null  object
 1   Full_Name           950000 non-null  object
 2   Age                 950000 non-null  int64
 3   Gender              950000 non-null  object
 4   Occupation          950000 non-null  object
 5   Grade_Level         950000 non-null  object
 6   Monthly_Income_GHS  950000 non-null  int64
 7   Region              950000 non-null  object
 8   Product_Applied     950000 non-null  object
 9   Smoker              950000 non-null  object
 10  BMI                 950000 non-null  float64
 11  Marital_Status      950000 non-null  object
 12  Dependents          950000 non-null  int64
 13  Premium_GHS         950000 non-null  float64
 14  Payment_Method      950000 non-null  object
 15  Application_Date    950000 non-null  object
 16  Policy_Status       950000 non-null  object
 17  Tenure_Months       950000 non-null  int64
 18  Payment_Behavior    950000 non-null  object
 19  Claim_Frequency     950000 non-null  int64
 20  Claim_Severity      400387 non-null  object
 21  Agent_ID            950000 non-null  object
 22  Agent_Name          950000 non-null  object
dtypes: float64(2), int64(5), object(16)
memory usage: 166.7+ MB

In [ ]:
customers.columns

Index(['Customer_ID', 'Full_Name', 'Age', 'Gender', 'Occupation',
       'Grade_Level', 'Monthly_Income_GHS', 'Region', 'Product_Applied',
       'Smoker', 'BMI', 'Marital_Status', 'Dependents', 'Premium_GHS',
       'Payment_Method', 'Application_Date', 'Policy_Status', 'Tenure_Months',
       'Payment_Behavior', 'Claim_Frequency', 'Claim_Severity', 'Agent_ID',
       'Agent_Name'],
      dtype='object')

In [ ]:
# Get unique list of customers
unique_customers = customers['Customer_ID'].unique()
unique_customers

array(['C0750001', 'C0750002', 'C0750003', ..., 'C0249998', 'C0249999',
       'C0250000'], dtype=object)

In [ ]:
# Count number of unique cutomers
len(unique_customers)

950000

In [ ]:
# Get unique list of customers_name
unique_customers_name = customers['Full_Name'].unique()
len(unique_customers_name)

40196

In [ ]:
duplicate_customers = customers[customers.duplicated(subset=['Full_Name'], keep=False)]
print(f"Number of duplicate customer names: {len(duplicate_customers)}")
display(duplicate_customers.sort_values(by='Full_Name'))

Number of duplicate customer names: 950000

,Customer_ID,Full_Name,Age,Gender,Occupation,Grade_Level,Monthly_Income_GHS,Region,Product_Applied,Smoker,...,Premium_GHS,Payment_Method,Application_Date,Policy_Status,Tenure_Months,Payment_Behavior,Claim_Frequency,Claim_Severity,Agent_ID,Agent_Name
298199,C0598200,Aaron Adams,25,Male,Medical Doctor,Junior,13357,Koforidua,Prudent Life Plan,No,...,687.92,Payroll Deduction,2025-07-02,Renewed,5,Consistent,1,Medium,AG023,Benjamin Nyarko
448199,C0748200,Aaron Adams,25,Male,Medical Doctor,Junior,13357,Koforidua,Prudent Life Plan,No,...,687.92,Payroll Deduction,2025-07-02,Renewed,5,Consistent,1,Medium,AG023,Benjamin Nyarko
98199,C0848200,Aaron Adams,25,Male,Medical Doctor,Junior,13357,Koforidua,Prudent Life Plan,No,...,687.92,Payroll Deduction,2025-07-02,Renewed,5,Consistent,1,Medium,AG023,Benjamin Nyarko
895135,C0195136,Aaron Adams,63,Female,Construction Worker,Junior,2522,Accra,Pru Wealth Plan,Yes,...,460.30,Bank Transfer,2025-11-16,Active,1,Consistent,1,Medium,AG006,Kelvin Arthur
545135,C0345136,Aaron Adams,63,Female,Construction Worker,Junior,2522,Accra,Pru Wealth Plan,Yes,...,460.30,Bank Transfer,2025-11-16,Active,1,Consistent,1,Medium,AG006,Kelvin Arthur
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
946535,C0246536,Zoe Williams,31,Male,Cybersecurity Specialist,Junior,10615,Koforidua,Pru Wealth Plan,No,...,377.44,Payroll Deduction,2024-12-07,Pending Renewal,12,Consistent,2,High,AG024,Gloria Asante
596535,C0396536,Zoe Williams,31,Male,Cybersecurity Specialist,Junior,10615,Koforidua,Pru Wealth Plan,No,...,377.44,Payroll Deduction,2024-12-07,Pending Renewal,12,Consistent,2,High,AG024,Gloria Asante
296535,C0596536,Zoe Williams,31,Male,Cybersecurity Specialist,Junior,10615,Koforidua,Pru Wealth Plan,No,...,377.44,Payroll Deduction,2024-12-07,Pending Renewal,12,Consistent,2,High,AG024,Gloria Asante
346535,C0646536,Zoe Williams,31,Male,Cybersecurity Specialist,Junior,10615,Koforidua,Pru Wealth Plan,No,...,377.44,Payroll Deduction,2024-12-07,Pending Renewal,12,Consistent,2,High,AG024,Gloria Asante
646535,C0446536,Zoe Williams,31,Male,Cybersecurity Specialist,Junior,10615,Koforidua,Pru Wealth Plan,No,...,377.44,Payroll Deduction,2024-12-07,Pending Renewal,12,Consistent,2,High,AG024,Gloria Asante

In [ ]:
customers[customers['Full_Name'].duplicated(keep=False)]

,Customer_ID,Full_Name,Age,Gender,Occupation,Grade_Level,Monthly_Income_GHS,Region,Product_Applied,Smoker,...,Premium_GHS,Payment_Method,Application_Date,Policy_Status,Tenure_Months,Payment_Behavior,Claim_Frequency,Claim_Severity,Agent_ID,Agent_Name
0,C0750001,Rachel Richardson,27,Female,Driver,Junior,2702,Takoradi,Mekakrawa,No,...,478.03,MoMo,2024-12-19,Cancelled,12,Frequently Late,0,NaN,AG013,Linda Nyarko
1,C0750002,Cody Macias,64,Male,Data Analyst,Junior,6314,Koforidua,Mekakrawa,Yes,...,417.29,MoMo,2024-10-23,Active,14,Occasionally Late,2,High,AG023,Benjamin Nyarko
2,C0750003,Joshua Brown,61,Male,Construction Worker,Mid,3048,Cape Coast,Prudential Travel Insurance Plan,Yes,...,945.59,Payroll Deduction,2025-11-05,Renewed,1,Consistent,2,High,AG017,Josephine Arthur
3,C0750004,Loretta Cross,48,Male,Software Engineer,Junior,7811,Kumasi,Mekakrawa,No,...,180.75,Bank Transfer,2024-05-12,Active,19,Occasionally Late,1,Low,AG011,Emmanuel Sarkodie
4,C0750005,Joshua Gonzalez,50,Male,Software Engineer,Senior,23078,Koforidua,Mekakrawa,Yes,...,670.93,Bank Transfer,2025-02-10,Pending Renewal,10,Consistent,1,Medium,AG023,Benjamin Nyarko
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
949995,C0249996,Nicole Perez,62,Female,Software Engineer,Junior,8809,Takoradi,Dignity Farewell Plan,Yes,...,201.52,MoMo,2024-02-28,Lapsed,22,Frequently Late,1,Low,AG013,Linda Nyarko
949996,C0249997,Angela Johnson,26,Male,Driver,Senior,4575,Sunyani,Prudential Travel Insurance Plan,Yes,...,678.61,MoMo,2025-09-11,Cancelled,3,Frequently Late,0,NaN,AG022,Collins Addae
949997,C0249998,Stephen Smith,46,Male,Accountant,Junior,4604,Kumasi,Pru Wealth Plan,No,...,283.88,Payroll Deduction,2024-06-01,Active,18,Consistent,0,NaN,AG009,Francis Annor
949998,C0249999,Alexa West,63,Female,Accountant,Senior,10315,Kumasi,Dignity Farewell Plan,Yes,...,534.50,Bank Transfer,2024-09-24,Lapsed,15,Occasionally Late,2,Medium,AG011,Emmanuel Sarkodie
949999,C0250000,Krystal Newman,25,Female,Software Engineer,Junior,7625,Koforidua,Mekakrawa,No,...,317.83,Payroll Deduction,2024-12-31,Active,12,Consistent,0,NaN,AG023,Benjamin Nyarko

In [ ]:
# Count duplicate full_name
customers['Full_Name'].duplicated().sum()

np.int64(909804)

In [ ]:
customers.duplicated().sum()

np.int64(0)

Scanning through customers reveal there are duplicate rows, however the customer_ID column is unique thus checking for duplicates with the customer_ID returns null. Drop the customer_ID column and check for duplicates

In [ ]:
# Drop customer_ID column to check for duplicates
customers_new = customers.drop(columns=['Customer_ID'])
customers_new.duplicated().sum()

np.int64(900000)

In [ ]:
# View duplicates
customers_new[customers_new.duplicated(keep=False)].sort_values(by=['Full_Name', 'Age', 'BMI'])

,Full_Name,Age,Gender,Occupation,Grade_Level,Monthly_Income_GHS,Region,Product_Applied,Smoker,BMI,...,Premium_GHS,Payment_Method,Application_Date,Policy_Status,Tenure_Months,Payment_Behavior,Claim_Frequency,Claim_Severity,Agent_ID,Agent_Name
48199,Aaron Adams,25,Male,Medical Doctor,Junior,13357,Koforidua,Prudent Life Plan,No,33.7,...,687.92,Payroll Deduction,2025-07-02,Renewed,5,Consistent,1,Medium,AG023,Benjamin Nyarko
98199,Aaron Adams,25,Male,Medical Doctor,Junior,13357,Koforidua,Prudent Life Plan,No,33.7,...,687.92,Payroll Deduction,2025-07-02,Renewed,5,Consistent,1,Medium,AG023,Benjamin Nyarko
148199,Aaron Adams,25,Male,Medical Doctor,Junior,13357,Koforidua,Prudent Life Plan,No,33.7,...,687.92,Payroll Deduction,2025-07-02,Renewed,5,Consistent,1,Medium,AG023,Benjamin Nyarko
198199,Aaron Adams,25,Male,Medical Doctor,Junior,13357,Koforidua,Prudent Life Plan,No,33.7,...,687.92,Payroll Deduction,2025-07-02,Renewed,5,Consistent,1,Medium,AG023,Benjamin Nyarko
248199,Aaron Adams,25,Male,Medical Doctor,Junior,13357,Koforidua,Prudent Life Plan,No,33.7,...,687.92,Payroll Deduction,2025-07-02,Renewed,5,Consistent,1,Medium,AG023,Benjamin Nyarko
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
746535,Zoe Williams,31,Male,Cybersecurity Specialist,Junior,10615,Koforidua,Pru Wealth Plan,No,35.3,...,377.44,Payroll Deduction,2024-12-07,Pending Renewal,12,Consistent,2,High,AG024,Gloria Asante
796535,Zoe Williams,31,Male,Cybersecurity Specialist,Junior,10615,Koforidua,Pru Wealth Plan,No,35.3,...,377.44,Payroll Deduction,2024-12-07,Pending Renewal,12,Consistent,2,High,AG024,Gloria Asante
846535,Zoe Williams,31,Male,Cybersecurity Specialist,Junior,10615,Koforidua,Pru Wealth Plan,No,35.3,...,377.44,Payroll Deduction,2024-12-07,Pending Renewal,12,Consistent,2,High,AG024,Gloria Asante
896535,Zoe Williams,31,Male,Cybersecurity Specialist,Junior,10615,Koforidua,Pru Wealth Plan,No,35.3,...,377.44,Payroll Deduction,2024-12-07,Pending Renewal,12,Consistent,2,High,AG024,Gloria Asante
946535,Zoe Williams,31,Male,Cybersecurity Specialist,Junior,10615,Koforidua,Pru Wealth Plan,No,35.3,...,377.44,Payroll Deduction,2024-12-07,Pending Renewal,12,Consistent,2,High,AG024,Gloria Asante

In [ ]:
print("Total rows:", len(customers_new))
print("Duplicate rows:", customers_new.duplicated().sum())
print("Unique rows:", len(customers_new.drop_duplicates()))

Total rows: 950000
Duplicate rows: 900000
Unique rows: 50000

In [ ]:
# Drop duplicates
customers_new = customers_new.drop_duplicates()
customers_new.sort_values(by='Full_Name')

,Full_Name,Age,Gender,Occupation,Grade_Level,Monthly_Income_GHS,Region,Product_Applied,Smoker,BMI,...,Premium_GHS,Payment_Method,Application_Date,Policy_Status,Tenure_Months,Payment_Behavior,Claim_Frequency,Claim_Severity,Agent_ID,Agent_Name
48199,Aaron Adams,25,Male,Medical Doctor,Junior,13357,Koforidua,Prudent Life Plan,No,33.7,...,687.92,Payroll Deduction,2025-07-02,Renewed,5,Consistent,1,Medium,AG023,Benjamin Nyarko
45135,Aaron Adams,63,Female,Construction Worker,Junior,2522,Accra,Pru Wealth Plan,Yes,20.3,...,460.30,Bank Transfer,2025-11-16,Active,1,Consistent,1,Medium,AG006,Kelvin Arthur
10245,Aaron Allen,31,Male,Civil Engineer,Junior,8405,Tamale,Dignity Farewell Plan,No,31.0,...,340.57,Payroll Deduction,2025-09-10,Renewed,3,Consistent,2,Medium,AG015,Naa Adoley
42939,Aaron Allen,61,Male,Accountant,Mid,7332,Accra,Mekakrawa,No,25.3,...,332.84,MoMo,2024-03-07,Pending Renewal,21,Consistent,2,Medium,AG001,Wisdom Festus
14554,Aaron Armstrong,59,Male,Accountant,Junior,4188,Accra,Prudent Life Plan,Yes,19.6,...,260.80,MoMo,2024-12-16,Pending Renewal,12,Consistent,0,NaN,AG007,Daniel Asare
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10293,Zoe Garcia,43,Male,Teacher,Junior,3361,Ho,Prudent Life Plan,No,32.2,...,531.91,Payroll Deduction,2024-09-25,Lapsed,15,Occasionally Late,1,Low,AG020,Isaac Tetteh
4459,Zoe Mills,23,Female,Construction Worker,Junior,1886,Ho,Prudent Life Plan,Yes,29.9,...,541.88,MoMo,2024-03-29,Active,21,Consistent,0,NaN,AG020,Isaac Tetteh
27560,Zoe Rocha,57,Male,Software Engineer,Junior,9349,Kumasi,Prudent Life Plan,Yes,26.8,...,573.74,Payroll Deduction,2024-03-25,Active,21,Consistent,1,Low,AG011,Emmanuel Sarkodie
30547,Zoe Simmons,21,Female,Accountant,Senior,11488,Tamale,Prudential Travel Insurance Plan,Yes,29.4,...,503.56,MoMo,2024-10-29,Active,14,Occasionally Late,0,NaN,AG016,Abena Boateng
46535,Zoe Williams,31,Male,Cybersecurity Specialist,Junior,10615,Koforidua,Pru Wealth Plan,No,35.3,...,377.44,Payroll Deduction,2024-12-07,Pending Renewal,12,Consistent,2,High,AG024,Gloria Asante

In [ ]:
# Create new Customer_ID column for PK purposes
customers_new.insert(0, 'Customer_ID', ['CUST' + str(i).zfill(3) for i in range(1, len(customers_new) + 1)])
customers_new

,Customer_ID,Full_Name,Age,Gender,Occupation,Grade_Level,Monthly_Income_GHS,Region,Product_Applied,Smoker,...,Premium_GHS,Payment_Method,Application_Date,Policy_Status,Tenure_Months,Payment_Behavior,Claim_Frequency,Claim_Severity,Agent_ID,Agent_Name
0,CUST001,Rachel Richardson,27,Female,Driver,Junior,2702,Takoradi,Mekakrawa,No,...,478.03,MoMo,2024-12-19,Cancelled,12,Frequently Late,0,NaN,AG013,Linda Nyarko
1,CUST002,Cody Macias,64,Male,Data Analyst,Junior,6314,Koforidua,Mekakrawa,Yes,...,417.29,MoMo,2024-10-23,Active,14,Occasionally Late,2,High,AG023,Benjamin Nyarko
2,CUST003,Joshua Brown,61,Male,Construction Worker,Mid,3048,Cape Coast,Prudential Travel Insurance Plan,Yes,...,945.59,Payroll Deduction,2025-11-05,Renewed,1,Consistent,2,High,AG017,Josephine Arthur
3,CUST004,Loretta Cross,48,Male,Software Engineer,Junior,7811,Kumasi,Mekakrawa,No,...,180.75,Bank Transfer,2024-05-12,Active,19,Occasionally Late,1,Low,AG011,Emmanuel Sarkodie
4,CUST005,Joshua Gonzalez,50,Male,Software Engineer,Senior,23078,Koforidua,Mekakrawa,Yes,...,670.93,Bank Transfer,2025-02-10,Pending Renewal,10,Consistent,1,Medium,AG023,Benjamin Nyarko
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,CUST49996,Nicole Perez,62,Female,Software Engineer,Junior,8809,Takoradi,Dignity Farewell Plan,Yes,...,201.52,MoMo,2024-02-28,Lapsed,22,Frequently Late,1,Low,AG013,Linda Nyarko
49996,CUST49997,Angela Johnson,26,Male,Driver,Senior,4575,Sunyani,Prudential Travel Insurance Plan,Yes,...,678.61,MoMo,2025-09-11,Cancelled,3,Frequently Late,0,NaN,AG022,Collins Addae
49997,CUST49998,Stephen Smith,46,Male,Accountant,Junior,4604,Kumasi,Pru Wealth Plan,No,...,283.88,Payroll Deduction,2024-06-01,Active,18,Consistent,0,NaN,AG009,Francis Annor
49998,CUST49999,Alexa West,63,Female,Accountant,Senior,10315,Kumasi,Dignity Farewell Plan,Yes,...,534.50,Bank Transfer,2024-09-24,Lapsed,15,Occasionally Late,2,Medium,AG011,Emmanuel Sarkodie
49999,CUST50000,Krystal Newman,25,Female,Software Engineer,Junior,7625,Koforidua,Mekakrawa,No,...,317.83,Payroll Deduction,2024-12-31,Active,12,Consistent,0,NaN,AG023,Benjamin Nyarko

In [ ]:
# Create customers_info table
customers_info = customers_new[['Customer_ID', 'Full_Name', 'Age', 'Gender', 'Occupation',
                            'Grade_Level', 'Monthly_Income_GHS', 'Region', 'Smoker',
                            'BMI', 'Marital_Status', 'Dependents']]

In [ ]:
# Preview customers_info
customers_info

,Customer_ID,Full_Name,Age,Gender,Occupation,Grade_Level,Monthly_Income_GHS,Region,Smoker,BMI,Marital_Status,Dependents
0,CUST001,Rachel Richardson,27,Female,Driver,Junior,2702,Takoradi,No,18.4,Married,1
1,CUST002,Cody Macias,64,Male,Data Analyst,Junior,6314,Koforidua,Yes,25.9,Married,3
2,CUST003,Joshua Brown,61,Male,Construction Worker,Mid,3048,Cape Coast,Yes,34.4,Single,3
3,CUST004,Loretta Cross,48,Male,Software Engineer,Junior,7811,Kumasi,No,22.6,Single,4
4,CUST005,Joshua Gonzalez,50,Male,Software Engineer,Senior,23078,Koforidua,Yes,23.7,Married,3
...,...,...,...,...,...,...,...,...,...,...,...,...
49995,CUST49996,Nicole Perez,62,Female,Software Engineer,Junior,8809,Takoradi,Yes,19.7,Single,4
49996,CUST49997,Angela Johnson,26,Male,Driver,Senior,4575,Sunyani,Yes,18.3,Divorced,0
49997,CUST49998,Stephen Smith,46,Male,Accountant,Junior,4604,Kumasi,No,24.6,Divorced,0
49998,CUST49999,Alexa West,63,Female,Accountant,Senior,10315,Kumasi,Yes,25.5,Married,2
49999,CUST50000,Krystal Newman,25,Female,Software Engineer,Junior,7625,Koforidua,No,29.2,Single,3

In [ ]:
# Extract customer_policies
customer_policies = customers_new[['Customer_ID','Product_Applied', 'Agent_ID',
                               'Premium_GHS','Payment_Method', 'Application_Date',
                               'Policy_Status', 'Tenure_Months','Payment_Behavior',
                                   'Claim_Frequency', 'Claim_Severity']]

In [ ]:
customer_policies

,Customer_ID,Product_Applied,Agent_ID,Premium_GHS,Payment_Method,Application_Date,Policy_Status,Tenure_Months,Payment_Behavior,Claim_Frequency,Claim_Severity
0,CUST001,Mekakrawa,AG013,478.03,MoMo,2024-12-19,Cancelled,12,Frequently Late,0,NaN
1,CUST002,Mekakrawa,AG023,417.29,MoMo,2024-10-23,Active,14,Occasionally Late,2,High
2,CUST003,Prudential Travel Insurance Plan,AG017,945.59,Payroll Deduction,2025-11-05,Renewed,1,Consistent,2,High
3,CUST004,Mekakrawa,AG011,180.75,Bank Transfer,2024-05-12,Active,19,Occasionally Late,1,Low
4,CUST005,Mekakrawa,AG023,670.93,Bank Transfer,2025-02-10,Pending Renewal,10,Consistent,1,Medium
...,...,...,...,...,...,...,...,...,...,...,...
49995,CUST49996,Dignity Farewell Plan,AG013,201.52,MoMo,2024-02-28,Lapsed,22,Frequently Late,1,Low
49996,CUST49997,Prudential Travel Insurance Plan,AG022,678.61,MoMo,2025-09-11,Cancelled,3,Frequently Late,0,NaN
49997,CUST49998,Pru Wealth Plan,AG009,283.88,Payroll Deduction,2024-06-01,Active,18,Consistent,0,NaN
49998,CUST49999,Dignity Farewell Plan,AG011,534.50,Bank Transfer,2024-09-24,Lapsed,15,Occasionally Late,2,Medium
49999,CUST50000,Mekakrawa,AG023,317.83,Payroll Deduction,2024-12-31,Active,12,Consistent,0,NaN

In [ ]:
# Create Agents table
agents = customers_new[['Agent_ID', 'Agent_Name']].drop_duplicates()
agents = agents.sort_values(by='Agent_ID')
agents.reset_index(drop=True, inplace=True)
agents

   Agent_ID         Agent_Name
0     AG001      Wisdom Festus
1     AG002        Sandra Kusi
2     AG003     Richard Tetteh
3     AG004      Michael Ofori
4     AG005     Priscilla Addo
5     AG006      Kelvin Arthur
6     AG007       Daniel Asare
7     AG008         Ama Mensah
8     AG009      Francis Annor
9     AG010   Patience Mensima
10    AG011  Emmanuel Sarkodie
11    AG012       Daniel Owusu
12    AG013       Linda Nyarko
13    AG014        Kwame Asare
14    AG015         Naa Adoley
15    AG016      Abena Boateng
16    AG017   Josephine Arthur
17    AG018   Stephen Kwarteng
18    AG019     Evelyn Agyeman
19    AG020       Isaac Tetteh
20    AG021         Mabel Osei
21    AG022      Collins Addae
22    AG023    Benjamin Nyarko
23    AG024      Gloria Asante

### **Corporate Insurance**: Create a Separate table for Corporate Clients to reduce data redundancy

In [ ]:

# preview the data
corporate_clients

,Corporate_ID,Company_Name,Branch_ID,Industry,Region,Number_of_Staff,Insurance_Product,Premium_Per_Staff_GHS,Insurance_Purpose,Application_Date
0,CORP001,MTN Ghana,BR001,Telecommunications,Accra,1800,Group Welfare Plan,248,HR Benefits,2025-11-15
1,CORP002,MTN Ghana,BR002,Telecommunications,Kumasi,250,Group Welfare Plan,254,Employee Welfare,2024-11-08
2,CORP003,MTN Ghana,BR003,Telecommunications,Takoradi,120,Group Funeral Insurance Plan,219,Talent Retention,2024-05-24
3,CORP004,MTN Ghana,BR004,Telecommunications,Tamale,80,Group Welfare Plan,232,Employee Welfare,2024-11-06
4,CORP005,MTN Ghana,BR005,Telecommunications,Ho,35,Group Life Insurance Plan,226,Employee Welfare,2024-03-06
...,...,...,...,...,...,...,...,...,...,...
65,CORP066,Enterprise Insurance,BR066,Insurance,Takoradi,35,Group Life Insurance Plan,179,Employee Welfare,2025-12-05
66,CORP067,MTN Ghana,BR067,Telecommunications,Accra,1800,Group Life Insurance Plan,256,Corporate Responsibility,2025-03-08
67,CORP068,MTN Ghana,BR068,Telecommunications,Kumasi,250,Group Welfare Plan,208,Talent Retention,2024-05-08
68,CORP069,MTN Ghana,BR069,Telecommunications,Takoradi,120,Group Welfare Plan,208,Corporate Responsibility,2025-06-25
69,CORP070,MTN Ghana,BR070,Telecommunications,Tamale,80,Group Funeral Insurance Plan,204,HR Benefits,2025-08-23

In [ ]:
# Get unique list of companies
unique_companies = corporate_clients['Company_Name'].unique()
unique_companies

array(['MTN Ghana', 'GCB Bank', 'Kasapreko Company Limited',
       'AngloGold Ashanti', 'Ashesi University', 'DHL Ghana',
       'Enterprise Insurance'], dtype=object)

In [ ]:
# Get unique list of Industry
unique_industry = corporate_clients['Industry'].unique()
unique_industry

array(['Telecommunications', 'Banking', 'Manufacturing', 'Mining',
       'Education', 'Logistics', 'Insurance'], dtype=object)

In [ ]:
companies = pd.DataFrame({
    'Company_Name': unique_companies,
    'Industry': unique_industry
})
companies

                Company_Name            Industry
0                  MTN Ghana  Telecommunications
1                   GCB Bank             Banking
2  Kasapreko Company Limited       Manufacturing
3          AngloGold Ashanti              Mining
4          Ashesi University           Education
5                  DHL Ghana           Logistics
6       Enterprise Insurance           Insurance

In [ ]:
# Add ID Column with code CORP001
companies.insert(0, 'ID', ['CORP' + str(i).zfill(3) for i in range(1, len(companies) + 1)])

In [ ]:
companies

        ID               Company_Name            Industry
0  CORP001                  MTN Ghana  Telecommunications
1  CORP002                   GCB Bank             Banking
2  CORP003  Kasapreko Company Limited       Manufacturing
3  CORP004          AngloGold Ashanti              Mining
4  CORP005          Ashesi University           Education
5  CORP006                  DHL Ghana           Logistics
6  CORP007       Enterprise Insurance           Insurance

## Create new Branch Table to reduce data redundancy

In [ ]:
# Select relevant columns from corporate_clients
branch = corporate_clients[['Branch_ID', 'Region', 'Number_of_Staff', 'Company_Name']]
branch

   Branch_ID    Region  Number_of_Staff          Company_Name
0      BR001     Accra             1800             MTN Ghana
1      BR002    Kumasi              250             MTN Ghana
2      BR003  Takoradi              120             MTN Ghana
3      BR004    Tamale               80             MTN Ghana
4      BR005        Ho               35             MTN Ghana
..       ...       ...              ...                   ...
65     BR066  Takoradi               35  Enterprise Insurance
66     BR067     Accra             1800             MTN Ghana
67     BR068    Kumasi              250             MTN Ghana
68     BR069  Takoradi              120             MTN Ghana
69     BR070    Tamale               80             MTN Ghana

[70 rows x 4 columns]

In [ ]:
# Merge branch with companies table to extract Company_ID
branch = branch.merge(companies, left_on='Company_Name', right_on='Company_Name', how='inner')
branch

,Branch_ID,Region,Number_of_Staff,Company_Name,ID,Industry
0,BR001,Accra,1800,MTN Ghana,CORP001,Telecommunications
1,BR002,Kumasi,250,MTN Ghana,CORP001,Telecommunications
2,BR003,Takoradi,120,MTN Ghana,CORP001,Telecommunications
3,BR004,Tamale,80,MTN Ghana,CORP001,Telecommunications
4,BR005,Ho,35,MTN Ghana,CORP001,Telecommunications
...,...,...,...,...,...,...
65,BR066,Takoradi,35,Enterprise Insurance,CORP007,Insurance
66,BR067,Accra,1800,MTN Ghana,CORP001,Telecommunications
67,BR068,Kumasi,250,MTN Ghana,CORP001,Telecommunications
68,BR069,Takoradi,120,MTN Ghana,CORP001,Telecommunications
69,BR070,Tamale,80,MTN Ghana,CORP001,Telecommunications

In [ ]:
# Drop irrelevant cols
branch.drop(['Company_Name', 'Industry'], axis=1, inplace=True, errors='ignore')
branch

   Branch_ID    Region  Number_of_Staff       ID
0      BR001     Accra             1800  CORP001
1      BR002    Kumasi              250  CORP001
2      BR003  Takoradi              120  CORP001
3      BR004    Tamale               80  CORP001
4      BR005        Ho               35  CORP001
..       ...       ...              ...      ...
65     BR066  Takoradi               35  CORP007
66     BR067     Accra             1800  CORP001
67     BR068    Kumasi              250  CORP001
68     BR069  Takoradi              120  CORP001
69     BR070    Tamale               80  CORP001

[70 rows x 4 columns]

In [ ]:
# Preview branch
branch.head()

  Branch_ID    Region  Number_of_Staff       ID
0     BR001     Accra             1800  CORP001
1     BR002    Kumasi              250  CORP001
2     BR003  Takoradi              120  CORP001
3     BR004    Tamale               80  CORP001
4     BR005        Ho               35  CORP001

In [ ]:
# Rename ID column to Company_ID in branch
branch.rename(columns={'ID': 'Corporate_ID'}, inplace=True)
branch

   Branch_ID    Region  Number_of_Staff Corporate_ID
0      BR001     Accra             1800      CORP001
1      BR002    Kumasi              250      CORP001
2      BR003  Takoradi              120      CORP001
3      BR004    Tamale               80      CORP001
4      BR005        Ho               35      CORP001
..       ...       ...              ...          ...
65     BR066  Takoradi               35      CORP007
66     BR067     Accra             1800      CORP001
67     BR068    Kumasi              250      CORP001
68     BR069  Takoradi              120      CORP001
69     BR070    Tamale               80      CORP001

[70 rows x 4 columns]

In [ ]:
# Change branch to branches
branches = branch
branches

   Branch_ID    Region  Number_of_Staff Corporate_ID
0      BR001     Accra             1800      CORP001
1      BR002    Kumasi              250      CORP001
2      BR003  Takoradi              120      CORP001
3      BR004    Tamale               80      CORP001
4      BR005        Ho               35      CORP001
..       ...       ...              ...          ...
65     BR066  Takoradi               35      CORP007
66     BR067     Accra             1800      CORP001
67     BR068    Kumasi              250      CORP001
68     BR069  Takoradi              120      CORP001
69     BR070    Tamale               80      CORP001

[70 rows x 4 columns]

## Modify Covered_Employees Table

In [ ]:
# Check for unique number of Corporate IDs
covered_employees['Corporate_ID'].nunique()

70

In [ ]:
covered_employees

,Employee_ID,Corporate_ID,Employee_Name,Occupation,Grade_Level,Monthly_Salary_GHS,Age,Gender,Dependents,Smoker
0,EMP00001,CORP001,April Perez,Network Engineer,Mid,12000,43,Male,2,Yes
1,EMP00002,CORP001,Jonathan Morris,Software Engineer,Junior,8500,40,Female,4,No
2,EMP00003,CORP001,Kathryn Cook,Network Engineer,Junior,7500,40,Male,4,No
3,EMP00004,CORP001,Christopher Johnson,Software Engineer,Mid,13000,51,Female,0,Yes
4,EMP00005,CORP001,Kenneth Thompson,Software Engineer,Junior,8500,58,Female,0,No
...,...,...,...,...,...,...,...,...,...,...
1969,EMP01970,CORP070,Megan Jones,Software Engineer,Mid,13000,53,Male,4,No
1970,EMP01971,CORP070,Teresa Lopez,Software Engineer,Senior,19000,53,Male,3,Yes
1971,EMP01972,CORP070,Mr. Daniel Ross,Network Engineer,Mid,12000,37,Female,0,Yes
1972,EMP01973,CORP070,Roy Smith,Network Engineer,Senior,17000,33,Male,0,Yes
1973,EMP01974,CORP070,James Mendoza,Network Engineer,Mid,12000,45,Female,1,No

### Observations
##### From companies, there are only 7 unique Corporate IDs
##### From Branch, there are 70 branches
##### Meanwhile from covered_employees there are 70 unique Corporate_IDs
##### Implying Corporate_ID in covered_employees is actually Branch IDs

In [ ]:
# Rename Corporate_ID in covered_employees to Branch_ID
covered_employees.rename(columns={'Corporate_ID' : 'Branch_ID'}, inplace=True)
covered_employees

,Employee_ID,Branch_ID,Employee_Name,Occupation,Grade_Level,Monthly_Salary_GHS,Age,Gender,Dependents,Smoker
0,EMP00001,CORP001,April Perez,Network Engineer,Mid,12000,43,Male,2,Yes
1,EMP00002,CORP001,Jonathan Morris,Software Engineer,Junior,8500,40,Female,4,No
2,EMP00003,CORP001,Kathryn Cook,Network Engineer,Junior,7500,40,Male,4,No
3,EMP00004,CORP001,Christopher Johnson,Software Engineer,Mid,13000,51,Female,0,Yes
4,EMP00005,CORP001,Kenneth Thompson,Software Engineer,Junior,8500,58,Female,0,No
...,...,...,...,...,...,...,...,...,...,...
1969,EMP01970,CORP070,Megan Jones,Software Engineer,Mid,13000,53,Male,4,No
1970,EMP01971,CORP070,Teresa Lopez,Software Engineer,Senior,19000,53,Male,3,Yes
1971,EMP01972,CORP070,Mr. Daniel Ross,Network Engineer,Mid,12000,37,Female,0,Yes
1972,EMP01973,CORP070,Roy Smith,Network Engineer,Senior,17000,33,Male,0,Yes
1973,EMP01974,CORP070,James Mendoza,Network Engineer,Mid,12000,45,Female,1,No

In [ ]:
# Change 'CORP' in Branch_ID to 'BR' to refelct branch_ID
covered_employees['Branch_ID'] = covered_employees['Branch_ID'].str.replace('CORP', 'BR')
covered_employees

,Employee_ID,Branch_ID,Employee_Name,Occupation,Grade_Level,Monthly_Salary_GHS,Age,Gender,Dependents,Smoker
0,EMP00001,BR001,April Perez,Network Engineer,Mid,12000,43,Male,2,Yes
1,EMP00002,BR001,Jonathan Morris,Software Engineer,Junior,8500,40,Female,4,No
2,EMP00003,BR001,Kathryn Cook,Network Engineer,Junior,7500,40,Male,4,No
3,EMP00004,BR001,Christopher Johnson,Software Engineer,Mid,13000,51,Female,0,Yes
4,EMP00005,BR001,Kenneth Thompson,Software Engineer,Junior,8500,58,Female,0,No
...,...,...,...,...,...,...,...,...,...,...
1969,EMP01970,BR070,Megan Jones,Software Engineer,Mid,13000,53,Male,4,No
1970,EMP01971,BR070,Teresa Lopez,Software Engineer,Senior,19000,53,Male,3,Yes
1971,EMP01972,BR070,Mr. Daniel Ross,Network Engineer,Mid,12000,37,Female,0,Yes
1972,EMP01973,BR070,Roy Smith,Network Engineer,Senior,17000,33,Male,0,Yes
1973,EMP01974,BR070,James Mendoza,Network Engineer,Mid,12000,45,Female,1,No

In [ ]:
covered_employees

,Employee_ID,Branch_ID,Employee_Name,Occupation,Grade_Level,Monthly_Salary_GHS,Age,Gender,Dependents,Smoker
0,EMP00001,BR001,April Perez,Network Engineer,Mid,12000,43,Male,2,Yes
1,EMP00002,BR001,Jonathan Morris,Software Engineer,Junior,8500,40,Female,4,No
2,EMP00003,BR001,Kathryn Cook,Network Engineer,Junior,7500,40,Male,4,No
3,EMP00004,BR001,Christopher Johnson,Software Engineer,Mid,13000,51,Female,0,Yes
4,EMP00005,BR001,Kenneth Thompson,Software Engineer,Junior,8500,58,Female,0,No
...,...,...,...,...,...,...,...,...,...,...
1969,EMP01970,BR070,Megan Jones,Software Engineer,Mid,13000,53,Male,4,No
1970,EMP01971,BR070,Teresa Lopez,Software Engineer,Senior,19000,53,Male,3,Yes
1971,EMP01972,BR070,Mr. Daniel Ross,Network Engineer,Mid,12000,37,Female,0,Yes
1972,EMP01973,BR070,Roy Smith,Network Engineer,Senior,17000,33,Male,0,Yes
1973,EMP01974,BR070,James Mendoza,Network Engineer,Mid,12000,45,Female,1,No

##### Challenge 1: Clean the Employee_Name column by extracting first name, middle name (if any) and last name
Explore APIs to assign genders

### Modify claims table

In [ ]:
# Preview claims
claims.head()

,Claim_ID,Employee_ID,Corporate_ID,Claim_Type,Claim_Amount_GHS,Claim_Status,Claim_Date
0,CLM00001,EMP01950,CORP069,Funeral Benefit,15040,Approved,2024-09-24
1,CLM00002,EMP00184,CORP007,Dental,7155,Rejected,2025-12-08
2,CLM00003,EMP00706,CORP027,Funeral Benefit,15572,Pending,2025-03-07
3,CLM00004,EMP01925,CORP069,Hospitalization,44381,Approved,2024-05-12
4,CLM00005,EMP01390,CORP049,Emergency Care,14988,Pending,2024-07-28

In [ ]:
# Corporte_ID is actually Branch_ID and is irrelevant on the claims table
# Drop Corporate_ID
claims.drop(columns=['Corporate_ID'], inplace=True)

In [ ]:
# Preview claims again
claims.head()

,Claim_ID,Employee_ID,Claim_Type,Claim_Amount_GHS,Claim_Status,Claim_Date
0,CLM00001,EMP01950,Funeral Benefit,15040,Approved,2024-09-24
1,CLM00002,EMP00184,Dental,7155,Rejected,2025-12-08
2,CLM00003,EMP00706,Funeral Benefit,15572,Pending,2025-03-07
3,CLM00004,EMP01925,Hospitalization,44381,Approved,2024-05-12
4,CLM00005,EMP01390,Emergency Care,14988,Pending,2024-07-28

#### Modify Premiums table

In [ ]:
# Preview premium_payments table
premium_payments.head()

,Payment_ID,Corporate_ID,Payment_Date,Amount_GHS,Payment_Status,Payment_Method
0,PAY00011,CORP001,2025-12-15,37200,Pending,Payroll Deduction
1,PAY00012,CORP001,2026-01-15,37200,Paid,Bank Transfer
2,PAY00013,CORP001,2026-02-15,37200,Paid,Payroll Deduction
3,PAY00014,CORP001,2026-03-15,37200,Paid,Bank Transfer
4,PAY00015,CORP001,2026-04-15,37200,Paid,Bank Transfer

###### From our observations, Corporate_ID should be 7 unique numbers

In [ ]:
# Check unique count of Corporate_ID in premium_payments
premium_payments['Corporate_ID'].nunique()

70

##### 70 Corporate_IDs in premium_payments suggest they are actually branch_IDs
Rename the column to branch_ID and change the prefix from CORP to BR

In [ ]:
# Rename Corporate_ID to Branch_ID in premium_payments
premium_payments.rename(columns={'Corporate_ID': 'Branch_ID'}, inplace=True)

In [ ]:
premium_payments

,Payment_ID,Branch_ID,Payment_Date,Amount_GHS,Payment_Status,Payment_Method
0,PAY00011,CORP001,2025-12-15,37200,Pending,Payroll Deduction
1,PAY00012,CORP001,2026-01-15,37200,Paid,Bank Transfer
2,PAY00013,CORP001,2026-02-15,37200,Paid,Payroll Deduction
3,PAY00014,CORP001,2026-03-15,37200,Paid,Bank Transfer
4,PAY00015,CORP001,2026-04-15,37200,Paid,Bank Transfer
...,...,...,...,...,...,...
415,PAY00702,CORP070,2025-10-23,16320,Paid,Bank Transfer
416,PAY00703,CORP070,2025-11-23,16320,Paid,Payroll Deduction
417,PAY00704,CORP070,2025-12-23,16320,Paid,Payroll Deduction
418,PAY00705,CORP070,2026-01-23,16320,Paid,Payroll Deduction
419,PAY00706,CORP070,2026-02-23,16320,Pending,Bank Transfer

In [ ]:
# Change 'CORP' prefix in Branch_ID to 'BR'
premium_payments['Branch_ID'] = premium_payments['Branch_ID'].str.replace('CORP', 'BR')

In [ ]:
premium_payments

,Payment_ID,Branch_ID,Payment_Date,Amount_GHS,Payment_Status,Payment_Method
0,PAY00011,BR001,2025-12-15,37200,Pending,Payroll Deduction
1,PAY00012,BR001,2026-01-15,37200,Paid,Bank Transfer
2,PAY00013,BR001,2026-02-15,37200,Paid,Payroll Deduction
3,PAY00014,BR001,2026-03-15,37200,Paid,Bank Transfer
4,PAY00015,BR001,2026-04-15,37200,Paid,Bank Transfer
...,...,...,...,...,...,...
415,PAY00702,BR070,2025-10-23,16320,Paid,Bank Transfer
416,PAY00703,BR070,2025-11-23,16320,Paid,Payroll Deduction
417,PAY00704,BR070,2025-12-23,16320,Paid,Payroll Deduction
418,PAY00705,BR070,2026-01-23,16320,Paid,Payroll Deduction
419,PAY00706,BR070,2026-02-23,16320,Pending,Bank Transfer

#### Modify Claims_workflow

In [ ]:
claim_workflow.head()

,Workflow_ID,Claim_ID,Submitted_Date,Reviewed_Date,Approved_By,Payout_Date
0,WF00001,CLM00001,2025-01-23,2025-01-27,Abena Ofori,NaN
1,WF00002,CLM00002,2024-06-12,2024-06-24,Michael Owusu,2024-07-04
2,WF00003,CLM00003,2025-10-15,2025-10-19,Daniel Asare,NaN
3,WF00004,CLM00004,2024-07-25,2024-07-28,Abena Ofori,NaN
4,WF00005,CLM00005,2024-09-16,2024-09-20,Kwame Mensah,2024-09-24

#### Modify Beneficiaries Table

In [ ]:
# Preview Beneficiaries table
beneficiaries.head()

,Beneficiary_ID,Employee_ID,Beneficiary_Name,Relationship,Allocation_Percentage
0,BEN00001,EMP00001,April Perez Family,Spouse,100
1,BEN00002,EMP00002,Jonathan Morris Family,Sibling,100
2,BEN00003,EMP00003,Kathryn Cook Family,Parent,100
3,BEN00004,EMP00004,Christopher Johnson Family,Sibling,100
4,BEN00005,EMP00005,Kenneth Thompson Family,Sibling,100

##### Modify Risk Score table

In [ ]:
# Preview risk_score table
risk_scores.head()

    Risk_ID Employee_ID
0  RSK00001    EMP00001
1  RSK00002    EMP00002
2  RSK00003    EMP00003
3  RSK00004    EMP00004
4  RSK00005    EMP00005

##### Modify Policy Table

In [ ]:
# Preview Policy table
policy_table.head()

,Policy_ID,Corporate_ID,Insurance_Product,Policy_Start_Date,Policy_End_Date,Policy_Status
0,POL0001,CORP001,Group Welfare Plan,2025-11-15,2026-11-15,Renewed
1,POL0002,CORP002,Group Welfare Plan,2024-11-08,2025-11-08,Renewed
2,POL0003,CORP003,Group Funeral Insurance Plan,2024-05-24,2025-05-24,Pending Renewal
3,POL0004,CORP004,Group Welfare Plan,2024-11-06,2025-11-06,Renewed
4,POL0005,CORP005,Group Life Insurance Plan,2024-03-06,2025-03-06,Pending Renewal

In [ ]:
# Count unique insurance_product
policy_table['Insurance_Product'].unique()

array(['Group Welfare Plan', 'Group Funeral Insurance Plan',
       'Group Life Insurance Plan'], dtype=object)

In [ ]:
# Check unique number of Corporate_IDs
policy_table['Corporate_ID'].nunique()

70

In [ ]:
# Rename Corporate_ID to Branch_ID
policy_table.rename(columns={'Corporate_ID' : 'Branch_ID'}, inplace=True)
policy_table

,Policy_ID,Branch_ID,Insurance_Product,Policy_Start_Date,Policy_End_Date,Policy_Status
0,POL0001,CORP001,Group Welfare Plan,2025-11-15,2026-11-15,Renewed
1,POL0002,CORP002,Group Welfare Plan,2024-11-08,2025-11-08,Renewed
2,POL0003,CORP003,Group Funeral Insurance Plan,2024-05-24,2025-05-24,Pending Renewal
3,POL0004,CORP004,Group Welfare Plan,2024-11-06,2025-11-06,Renewed
4,POL0005,CORP005,Group Life Insurance Plan,2024-03-06,2025-03-06,Pending Renewal
...,...,...,...,...,...,...
65,POL0066,CORP066,Group Life Insurance Plan,2025-12-05,2026-12-05,Renewed
66,POL0067,CORP067,Group Life Insurance Plan,2025-03-08,2026-03-08,Renewed
67,POL0068,CORP068,Group Welfare Plan,2024-05-08,2025-05-08,Active
68,POL0069,CORP069,Group Welfare Plan,2025-06-25,2026-06-25,Pending Renewal
69,POL0070,CORP070,Group Funeral Insurance Plan,2025-08-23,2026-08-23,Active

In [ ]:
# Change 'CORP' prefix in Branch_ID to 'BR
policy_table['Branch_ID'] = policy_table['Branch_ID'].str.replace('CORP', 'BR')
policy_table

,Policy_ID,Branch_ID,Insurance_Product,Policy_Start_Date,Policy_End_Date,Policy_Status
0,POL0001,BR001,Group Welfare Plan,2025-11-15,2026-11-15,Renewed
1,POL0002,BR002,Group Welfare Plan,2024-11-08,2025-11-08,Renewed
2,POL0003,BR003,Group Funeral Insurance Plan,2024-05-24,2025-05-24,Pending Renewal
3,POL0004,BR004,Group Welfare Plan,2024-11-06,2025-11-06,Renewed
4,POL0005,BR005,Group Life Insurance Plan,2024-03-06,2025-03-06,Pending Renewal
...,...,...,...,...,...,...
65,POL0066,BR066,Group Life Insurance Plan,2025-12-05,2026-12-05,Renewed
66,POL0067,BR067,Group Life Insurance Plan,2025-03-08,2026-03-08,Renewed
67,POL0068,BR068,Group Welfare Plan,2024-05-08,2025-05-08,Active
68,POL0069,BR069,Group Welfare Plan,2025-06-25,2026-06-25,Pending Renewal
69,POL0070,BR070,Group Funeral Insurance Plan,2025-08-23,2026-08-23,Active

In [ ]:
# CHeck corporate_clients table
corporate_clients.head()

,Corporate_ID,Company_Name,Branch_ID,Industry,Region,Number_of_Staff,Insurance_Product,Premium_Per_Staff_GHS,Insurance_Purpose,Application_Date
0,CORP001,MTN Ghana,BR001,Telecommunications,Accra,1800,Group Welfare Plan,248,HR Benefits,2025-11-15
1,CORP002,MTN Ghana,BR002,Telecommunications,Kumasi,250,Group Welfare Plan,254,Employee Welfare,2024-11-08
2,CORP003,MTN Ghana,BR003,Telecommunications,Takoradi,120,Group Funeral Insurance Plan,219,Talent Retention,2024-05-24
3,CORP004,MTN Ghana,BR004,Telecommunications,Tamale,80,Group Welfare Plan,232,Employee Welfare,2024-11-06
4,CORP005,MTN Ghana,BR005,Telecommunications,Ho,35,Group Life Insurance Plan,226,Employee Welfare,2024-03-06

In [ ]:
corporate_clients['Corporate_ID'].nunique()

70

checking the corporate_clients table reveal some redundant cols therein and no primary key

In [ ]:
# Remove redundant cols
corporate_clients.drop(columns=['Company_Name', 'Industry', 'Region', 'Number_of_Staff'], inplace=True)
corporate_clients

,Corporate_ID,Branch_ID,Insurance_Product,Premium_Per_Staff_GHS,Insurance_Purpose,Application_Date
0,CORP001,BR001,Group Welfare Plan,248,HR Benefits,2025-11-15
1,CORP002,BR002,Group Welfare Plan,254,Employee Welfare,2024-11-08
2,CORP003,BR003,Group Funeral Insurance Plan,219,Talent Retention,2024-05-24
3,CORP004,BR004,Group Welfare Plan,232,Employee Welfare,2024-11-06
4,CORP005,BR005,Group Life Insurance Plan,226,Employee Welfare,2024-03-06
...,...,...,...,...,...,...
65,CORP066,BR066,Group Life Insurance Plan,179,Employee Welfare,2025-12-05
66,CORP067,BR067,Group Life Insurance Plan,256,Corporate Responsibility,2025-03-08
67,CORP068,BR068,Group Welfare Plan,208,Talent Retention,2024-05-08
68,CORP069,BR069,Group Welfare Plan,208,Corporate Responsibility,2025-06-25
69,CORP070,BR070,Group Funeral Insurance Plan,204,HR Benefits,2025-08-23

In [ ]:
# Rename Corporate_ID col to Insurance_ID and make primary key
corporate_clients.rename(columns={'Corporate_ID' : 'Insurance_ID'}, inplace=True)
corporate_clients

,Insurance_ID,Branch_ID,Insurance_Product,Premium_Per_Staff_GHS,Insurance_Purpose,Application_Date
0,CORP001,BR001,Group Welfare Plan,248,HR Benefits,2025-11-15
1,CORP002,BR002,Group Welfare Plan,254,Employee Welfare,2024-11-08
2,CORP003,BR003,Group Funeral Insurance Plan,219,Talent Retention,2024-05-24
3,CORP004,BR004,Group Welfare Plan,232,Employee Welfare,2024-11-06
4,CORP005,BR005,Group Life Insurance Plan,226,Employee Welfare,2024-03-06
...,...,...,...,...,...,...
65,CORP066,BR066,Group Life Insurance Plan,179,Employee Welfare,2025-12-05
66,CORP067,BR067,Group Life Insurance Plan,256,Corporate Responsibility,2025-03-08
67,CORP068,BR068,Group Welfare Plan,208,Talent Retention,2024-05-08
68,CORP069,BR069,Group Welfare Plan,208,Corporate Responsibility,2025-06-25
69,CORP070,BR070,Group Funeral Insurance Plan,204,HR Benefits,2025-08-23

In [ ]:
# Replace prefix from 'CORP' to 'INS' in Insurance_ID col
corporate_clients['Insurance_ID'] = corporate_clients['Insurance_ID'].str.replace('CORP', 'INS')
corporate_clients

,Insurance_ID,Branch_ID,Insurance_Product,Premium_Per_Staff_GHS,Insurance_Purpose,Application_Date
0,INS001,BR001,Group Welfare Plan,248,HR Benefits,2025-11-15
1,INS002,BR002,Group Welfare Plan,254,Employee Welfare,2024-11-08
2,INS003,BR003,Group Funeral Insurance Plan,219,Talent Retention,2024-05-24
3,INS004,BR004,Group Welfare Plan,232,Employee Welfare,2024-11-06
4,INS005,BR005,Group Life Insurance Plan,226,Employee Welfare,2024-03-06
...,...,...,...,...,...,...
65,INS066,BR066,Group Life Insurance Plan,179,Employee Welfare,2025-12-05
66,INS067,BR067,Group Life Insurance Plan,256,Corporate Responsibility,2025-03-08
67,INS068,BR068,Group Welfare Plan,208,Talent Retention,2024-05-08
68,INS069,BR069,Group Welfare Plan,208,Corporate Responsibility,2025-06-25
69,INS070,BR070,Group Funeral Insurance Plan,204,HR Benefits,2025-08-23

In [ ]:
# Rename corporate_client df to insurance df
corporate_insurance = corporate_clients
corporate_insurance

,Insurance_ID,Branch_ID,Insurance_Product,Premium_Per_Staff_GHS,Insurance_Purpose,Application_Date
0,INS001,BR001,Group Welfare Plan,248,HR Benefits,2025-11-15
1,INS002,BR002,Group Welfare Plan,254,Employee Welfare,2024-11-08
2,INS003,BR003,Group Funeral Insurance Plan,219,Talent Retention,2024-05-24
3,INS004,BR004,Group Welfare Plan,232,Employee Welfare,2024-11-06
4,INS005,BR005,Group Life Insurance Plan,226,Employee Welfare,2024-03-06
...,...,...,...,...,...,...
65,INS066,BR066,Group Life Insurance Plan,179,Employee Welfare,2025-12-05
66,INS067,BR067,Group Life Insurance Plan,256,Corporate Responsibility,2025-03-08
67,INS068,BR068,Group Welfare Plan,208,Talent Retention,2024-05-08
68,INS069,BR069,Group Welfare Plan,208,Corporate Responsibility,2025-06-25
69,INS070,BR070,Group Funeral Insurance Plan,204,HR Benefits,2025-08-23

In [ ]:
policy_table

,Policy_ID,Branch_ID,Insurance_Product,Policy_Start_Date,Policy_End_Date,Policy_Status
0,POL0001,BR001,Group Welfare Plan,2025-11-15,2026-11-15,Renewed
1,POL0002,BR002,Group Welfare Plan,2024-11-08,2025-11-08,Renewed
2,POL0003,BR003,Group Funeral Insurance Plan,2024-05-24,2025-05-24,Pending Renewal
3,POL0004,BR004,Group Welfare Plan,2024-11-06,2025-11-06,Renewed
4,POL0005,BR005,Group Life Insurance Plan,2024-03-06,2025-03-06,Pending Renewal
...,...,...,...,...,...,...
65,POL0066,BR066,Group Life Insurance Plan,2025-12-05,2026-12-05,Renewed
66,POL0067,BR067,Group Life Insurance Plan,2025-03-08,2026-03-08,Renewed
67,POL0068,BR068,Group Welfare Plan,2024-05-08,2025-05-08,Active
68,POL0069,BR069,Group Welfare Plan,2025-06-25,2026-06-25,Pending Renewal
69,POL0070,BR070,Group Funeral Insurance Plan,2025-08-23,2026-08-23,Active

In [ ]:
# Change corporate ID col to Branch_ID col in policy_table
policy_table.rename(columns={'Corporate_ID' : 'Branch_ID'}, inplace=True)
policy_table

,Policy_ID,Branch_ID,Insurance_Product,Policy_Start_Date,Policy_End_Date,Policy_Status
0,POL0001,BR001,Group Welfare Plan,2025-11-15,2026-11-15,Renewed
1,POL0002,BR002,Group Welfare Plan,2024-11-08,2025-11-08,Renewed
2,POL0003,BR003,Group Funeral Insurance Plan,2024-05-24,2025-05-24,Pending Renewal
3,POL0004,BR004,Group Welfare Plan,2024-11-06,2025-11-06,Renewed
4,POL0005,BR005,Group Life Insurance Plan,2024-03-06,2025-03-06,Pending Renewal
...,...,...,...,...,...,...
65,POL0066,BR066,Group Life Insurance Plan,2025-12-05,2026-12-05,Renewed
66,POL0067,BR067,Group Life Insurance Plan,2025-03-08,2026-03-08,Renewed
67,POL0068,BR068,Group Welfare Plan,2024-05-08,2025-05-08,Active
68,POL0069,BR069,Group Welfare Plan,2025-06-25,2026-06-25,Pending Renewal
69,POL0070,BR070,Group Funeral Insurance Plan,2025-08-23,2026-08-23,Active

In [ ]:
# Change the prefix Branch_ID from 'CORP' to 'BR' in policy_table
policy_table['Branch_ID'] = policy_table['Branch_ID'].str.replace('CORP', 'BR')
policy_table

,Policy_ID,Branch_ID,Insurance_Product,Policy_Start_Date,Policy_End_Date,Policy_Status
0,POL0001,BR001,Group Welfare Plan,2025-11-15,2026-11-15,Renewed
1,POL0002,BR002,Group Welfare Plan,2024-11-08,2025-11-08,Renewed
2,POL0003,BR003,Group Funeral Insurance Plan,2024-05-24,2025-05-24,Pending Renewal
3,POL0004,BR004,Group Welfare Plan,2024-11-06,2025-11-06,Renewed
4,POL0005,BR005,Group Life Insurance Plan,2024-03-06,2025-03-06,Pending Renewal
...,...,...,...,...,...,...
65,POL0066,BR066,Group Life Insurance Plan,2025-12-05,2026-12-05,Renewed
66,POL0067,BR067,Group Life Insurance Plan,2025-03-08,2026-03-08,Renewed
67,POL0068,BR068,Group Welfare Plan,2024-05-08,2025-05-08,Active
68,POL0069,BR069,Group Welfare Plan,2025-06-25,2026-06-25,Pending Renewal
69,POL0070,BR070,Group Funeral Insurance Plan,2025-08-23,2026-08-23,Active

In [ ]:
# Create an insurance_product table to link corporate insurance and retail insurance
insurance_products = corporate_insurance[['Insurance_ID','Insurance_Product', 'Insurance_Purpose']].drop_duplicates()
insurance_products

   Insurance_ID             Insurance_Product         Insurance_Purpose
0        INS001            Group Welfare Plan               HR Benefits
1        INS002            Group Welfare Plan          Employee Welfare
2        INS003  Group Funeral Insurance Plan          Talent Retention
3        INS004            Group Welfare Plan          Employee Welfare
4        INS005     Group Life Insurance Plan          Employee Welfare
..          ...                           ...                       ...
65       INS066     Group Life Insurance Plan          Employee Welfare
66       INS067     Group Life Insurance Plan  Corporate Responsibility
67       INS068            Group Welfare Plan          Talent Retention
68       INS069            Group Welfare Plan  Corporate Responsibility
69       INS070  Group Funeral Insurance Plan               HR Benefits

[70 rows x 3 columns]

In [ ]:
# in insurance_products, check for unique insurance_id
insurance_products['Insurance_Purpose'].unique()

array(['HR Benefits', 'Employee Welfare', 'Talent Retention',
       'Corporate Responsibility'], dtype=object)

In [ ]:
# drop Insurnace_ID to check for duplicates
insurance_products.drop(columns=['Insurance_ID'], inplace=True)
insurance_products

               Insurance_Product         Insurance_Purpose
0             Group Welfare Plan               HR Benefits
1             Group Welfare Plan          Employee Welfare
2   Group Funeral Insurance Plan          Talent Retention
3             Group Welfare Plan          Employee Welfare
4      Group Life Insurance Plan          Employee Welfare
..                           ...                       ...
65     Group Life Insurance Plan          Employee Welfare
66     Group Life Insurance Plan  Corporate Responsibility
67            Group Welfare Plan          Talent Retention
68            Group Welfare Plan  Corporate Responsibility
69  Group Funeral Insurance Plan               HR Benefits

[70 rows x 2 columns]

In [ ]:
# drop duplicates
insurance_products.drop_duplicates(inplace=True)
insurance_products

               Insurance_Product         Insurance_Purpose
0             Group Welfare Plan               HR Benefits
1             Group Welfare Plan          Employee Welfare
2   Group Funeral Insurance Plan          Talent Retention
4      Group Life Insurance Plan          Employee Welfare
6      Group Life Insurance Plan          Talent Retention
7   Group Funeral Insurance Plan  Corporate Responsibility
13            Group Welfare Plan          Talent Retention
15  Group Funeral Insurance Plan               HR Benefits
16  Group Funeral Insurance Plan          Employee Welfare
25     Group Life Insurance Plan  Corporate Responsibility
27     Group Life Insurance Plan               HR Benefits
45            Group Welfare Plan  Corporate Responsibility

In [ ]:
# get unique values of product_applied from customer_policies
customer_policies['Product_Applied'].unique()

array(['Mekakrawa', 'Prudential Travel Insurance Plan', 'Pru Wealth Plan',
       'Ultimate Premier Farewell Plan', 'Prudent Life Plan',
       'Dignity Farewell Plan'], dtype=object)

In [ ]:
# get unique values of insurance_products from corporate_insurance
corporate_insurance['Insurance_Product'].unique()

array(['Group Welfare Plan', 'Group Funeral Insurance Plan',
       'Group Life Insurance Plan'], dtype=object)

In [ ]:
corporate_products = corporate_insurance['Insurance_Product'].unique()
retail_products = customer_policies['Product_Applied'].unique()

# Combine both arrays of unique products and convert to a Series, then drop duplicates
all_unique_products = pd.Series(list(corporate_products) + list(retail_products)).drop_duplicates()

# Create a new DataFrame for insurance_products with a single column for product names
insurance_products = pd.DataFrame({'Product_Name': all_unique_products}).reset_index(drop=True)
insurance_products

                       Product_Name
0                Group Welfare Plan
1      Group Funeral Insurance Plan
2         Group Life Insurance Plan
3                         Mekakrawa
4  Prudential Travel Insurance Plan
5                   Pru Wealth Plan
6    Ultimate Premier Farewell Plan
7                 Prudent Life Plan
8             Dignity Farewell Plan

### Creating unique `Insurance_Product_ID` and linking to other tables

In [ ]:
# Generate a unique ID for each insurance product
insurance_products['Product_ID'] = ['INSP' + str(i).zfill(3) for i in range(1, len(insurance_products) + 1)]

# Reorder columns and display
insurance_products = insurance_products[['Product_ID', 'Product_Name']]
insurance_products

  Product_ID                      Product_Name
0    INSP001                Group Welfare Plan
1    INSP002      Group Funeral Insurance Plan
2    INSP003         Group Life Insurance Plan
3    INSP004                         Mekakrawa
4    INSP005  Prudential Travel Insurance Plan
5    INSP006                   Pru Wealth Plan
6    INSP007    Ultimate Premier Farewell Plan
7    INSP008                 Prudent Life Plan
8    INSP009             Dignity Farewell Plan

#### Linking `policy_table` with `insurance_products`

In [ ]:
# Merge policy_table with insurance_products to get Insurance_Product_ID
policy_table = policy_table.merge(insurance_products, left_on='Insurance_Product', right_on='Product_Name', how='left')

# Drop the original 'Insurance_Product' and 'Product_Name' columns
policy_table.drop(columns=['Insurance_Product', 'Product_Name'], inplace=True)

# Reorder columns to place Insurance_Product_ID after Policy_ID
policy_table = policy_table[['Policy_ID', 'Branch_ID', 'Product_ID', 'Policy_Start_Date', 'Policy_End_Date', 'Policy_Status']]
policy_table

,Policy_ID,Branch_ID,Product_ID,Policy_Start_Date,Policy_End_Date,Policy_Status
0,POL0001,BR001,INSP001,2025-11-15,2026-11-15,Renewed
1,POL0002,BR002,INSP001,2024-11-08,2025-11-08,Renewed
2,POL0003,BR003,INSP002,2024-05-24,2025-05-24,Pending Renewal
3,POL0004,BR004,INSP001,2024-11-06,2025-11-06,Renewed
4,POL0005,BR005,INSP003,2024-03-06,2025-03-06,Pending Renewal
...,...,...,...,...,...,...
65,POL0066,BR066,INSP003,2025-12-05,2026-12-05,Renewed
66,POL0067,BR067,INSP003,2025-03-08,2026-03-08,Renewed
67,POL0068,BR068,INSP001,2024-05-08,2025-05-08,Active
68,POL0069,BR069,INSP001,2025-06-25,2026-06-25,Pending Renewal
69,POL0070,BR070,INSP002,2025-08-23,2026-08-23,Active

Linking insurance_products to customer_policies

In [ ]:
# Linking insurance_products to customer_policies
customer_policies = customer_policies.merge(insurance_products, left_on='Product_Applied', right_on='Product_Name', how='left')
customer_policies.drop(columns=['Product_Applied', 'Product_Name'], inplace=True)
customer_policies = customer_policies[['Customer_ID', 'Product_ID', 'Agent_ID', 'Premium_GHS', 'Payment_Method', 'Application_Date', 'Policy_Status', 'Tenure_Months', 'Payment_Behavior', 'Claim_Frequency', 'Claim_Severity']]

In [ ]:
# preview customer_policies
customer_policies

,Customer_ID,Product_ID,Agent_ID,Premium_GHS,Payment_Method,Application_Date,Policy_Status,Tenure_Months,Payment_Behavior,Claim_Frequency,Claim_Severity
0,CUST001,INSP004,AG013,478.03,MoMo,2024-12-19,Cancelled,12,Frequently Late,0,NaN
1,CUST002,INSP004,AG023,417.29,MoMo,2024-10-23,Active,14,Occasionally Late,2,High
2,CUST003,INSP005,AG017,945.59,Payroll Deduction,2025-11-05,Renewed,1,Consistent,2,High
3,CUST004,INSP004,AG011,180.75,Bank Transfer,2024-05-12,Active,19,Occasionally Late,1,Low
4,CUST005,INSP004,AG023,670.93,Bank Transfer,2025-02-10,Pending Renewal,10,Consistent,1,Medium
...,...,...,...,...,...,...,...,...,...,...,...
49995,CUST49996,INSP009,AG013,201.52,MoMo,2024-02-28,Lapsed,22,Frequently Late,1,Low
49996,CUST49997,INSP005,AG022,678.61,MoMo,2025-09-11,Cancelled,3,Frequently Late,0,NaN
49997,CUST49998,INSP006,AG009,283.88,Payroll Deduction,2024-06-01,Active,18,Consistent,0,NaN
49998,CUST49999,INSP009,AG011,534.50,Bank Transfer,2024-09-24,Lapsed,15,Occasionally Late,2,Medium
49999,CUST50000,INSP004,AG023,317.83,Payroll Deduction,2024-12-31,Active,12,Consistent,0,NaN

Linking insurance_products to corporate_insurance

In [ ]:
# Linking corporate_insurance to insurance_products
corporate_insurance = corporate_insurance.merge(insurance_products, left_on='Insurance_Product', right_on='Product_Name', how='left')
corporate_insurance.drop(columns=['Insurance_Product', 'Product_Name'], inplace=True)
corporate_insurance

,Insurance_ID,Branch_ID,Premium_Per_Staff_GHS,Insurance_Purpose,Application_Date,Product_ID
0,INS001,BR001,248,HR Benefits,2025-11-15,INSP001
1,INS002,BR002,254,Employee Welfare,2024-11-08,INSP001
2,INS003,BR003,219,Talent Retention,2024-05-24,INSP002
3,INS004,BR004,232,Employee Welfare,2024-11-06,INSP001
4,INS005,BR005,226,Employee Welfare,2024-03-06,INSP003
...,...,...,...,...,...,...
65,INS066,BR066,179,Employee Welfare,2025-12-05,INSP003
66,INS067,BR067,256,Corporate Responsibility,2025-03-08,INSP003
67,INS068,BR068,208,Talent Retention,2024-05-08,INSP001
68,INS069,BR069,208,Corporate Responsibility,2025-06-25,INSP001
69,INS070,BR070,204,HR Benefits,2025-08-23,INSP002

In [ ]:
policy_table

,Policy_ID,Branch_ID,Product_ID,Policy_Start_Date,Policy_End_Date,Policy_Status
0,POL0001,BR001,INSP001,2025-11-15,2026-11-15,Renewed
1,POL0002,BR002,INSP001,2024-11-08,2025-11-08,Renewed
2,POL0003,BR003,INSP002,2024-05-24,2025-05-24,Pending Renewal
3,POL0004,BR004,INSP001,2024-11-06,2025-11-06,Renewed
4,POL0005,BR005,INSP003,2024-03-06,2025-03-06,Pending Renewal
...,...,...,...,...,...,...
65,POL0066,BR066,INSP003,2025-12-05,2026-12-05,Renewed
66,POL0067,BR067,INSP003,2025-03-08,2026-03-08,Renewed
67,POL0068,BR068,INSP001,2024-05-08,2025-05-08,Active
68,POL0069,BR069,INSP001,2025-06-25,2026-06-25,Pending Renewal
69,POL0070,BR070,INSP002,2025-08-23,2026-08-23,Active

In [ ]:
tables = {
    'companies': companies,
    'branches': branches,
    'covered_employees': covered_employees,
    'claims': claims,
    'premium_payments': premium_payments,
    'claim_workflow': claim_workflow,
    'beneficiaries': beneficiaries,
    'policy_table': policy_table,
    'customers_info': customers_info,
    'customer_policies': customer_policies,
    'agents': agents,
    'corporate_insurance': corporate_insurance,
    'insurance_products': insurance_products

}

In [ ]:
for key, value in tables.items():
  print(key)
  print(value.columns)

companies
Index(['ID', 'Company_Name', 'Industry'], dtype='object')
branches
Index(['Branch_ID', 'Region', 'Number_of_Staff', 'Corporate_ID'], dtype='object')
covered_employees
Index(['Employee_ID', 'Branch_ID', 'Employee_Name', 'Occupation',
       'Grade_Level', 'Monthly_Salary_GHS', 'Age', 'Gender', 'Dependents',
       'Smoker'],
      dtype='object')
claims
Index(['Claim_ID', 'Employee_ID', 'Claim_Type', 'Claim_Amount_GHS',
       'Claim_Status', 'Claim_Date'],
      dtype='object')
premium_payments
Index(['Payment_ID', 'Branch_ID', 'Payment_Date', 'Amount_GHS',
       'Payment_Status', 'Payment_Method'],
      dtype='object')
claim_workflow
Index(['Workflow_ID', 'Claim_ID', 'Submitted_Date', 'Reviewed_Date',
       'Approved_By', 'Payout_Date'],
      dtype='object')
beneficiaries
Index(['Beneficiary_ID', 'Employee_ID', 'Beneficiary_Name', 'Relationship',
       'Allocation_Percentage'],
      dtype='object')
policy_table
Index(['Policy_ID', 'Branch_ID', 'Product_ID', 'Policy_Start_Date',
       'Policy_End_Date', 'Policy_Status'],
      dtype='object')
customers_info
Index(['Customer_ID', 'Full_Name', 'Age', 'Gender', 'Occupation',
       'Grade_Level', 'Monthly_Income_GHS', 'Region', 'Smoker', 'BMI',
       'Marital_Status', 'Dependents'],
      dtype='object')
customer_policies
Index(['Customer_ID', 'Product_ID', 'Agent_ID', 'Premium_GHS',
       'Payment_Method', 'Application_Date', 'Policy_Status', 'Tenure_Months',
       'Payment_Behavior', 'Claim_Frequency', 'Claim_Severity'],
      dtype='object')
agents
Index(['Agent_ID', 'Agent_Name'], dtype='object')
corporate_insurance
Index(['Insurance_ID', 'Branch_ID', 'Premium_Per_Staff_GHS',
       'Insurance_Purpose', 'Application_Date', 'Product_ID'],
      dtype='object')
insurance_products
Index(['Product_ID', 'Product_Name'], dtype='object')

In [ ]:
# Check dtypes before exporting into BigQuery
for key, value in tables.items():
  print(key)
  print(value.dtypes)
  print('\n')

companies
ID              object
Company_Name    object
Industry        object
dtype: object


branches
Branch_ID          object
Region             object
Number_of_Staff     int64
Corporate_ID       object
dtype: object


covered_employees
Employee_ID           object
Branch_ID             object
Employee_Name         object
Occupation            object
Grade_Level           object
Monthly_Salary_GHS     int64
Age                    int64
Gender                object
Dependents             int64
Smoker                object
dtype: object


claims
Claim_ID            object
Employee_ID         object
Claim_Type          object
Claim_Amount_GHS     int64
Claim_Status        object
Claim_Date          object
dtype: object


premium_payments
Payment_ID        object
Branch_ID         object
Payment_Date      object
Amount_GHS         int64
Payment_Status    object
Payment_Method    object
dtype: object


claim_workflow
Workflow_ID       object
Claim_ID          object
Submitted_Date    object
Reviewed_Date     object
Approved_By       object
Payout_Date       object
dtype: object


beneficiaries
Beneficiary_ID           object
Employee_ID              object
Beneficiary_Name         object
Relationship             object
Allocation_Percentage     int64
dtype: object


policy_table
Policy_ID            object
Branch_ID            object
Product_ID           object
Policy_Start_Date    object
Policy_End_Date      object
Policy_Status        object
dtype: object


customers_info
Customer_ID            object
Full_Name              object
Age                     int64
Gender                 object
Occupation             object
Grade_Level            object
Monthly_Income_GHS      int64
Region                 object
Smoker                 object
BMI                   float64
Marital_Status         object
Dependents              int64
dtype: object


customer_policies
Customer_ID          object
Product_ID           object
Agent_ID             object
Premium_GHS         float64
Payment_Method       object
Application_Date     object
Policy_Status        object
Tenure_Months         int64
Payment_Behavior     object
Claim_Frequency       int64
Claim_Severity       object
dtype: object


agents
Agent_ID      object
Agent_Name    object
dtype: object


corporate_insurance
Insurance_ID             object
Branch_ID                object
Premium_Per_Staff_GHS     int64
Insurance_Purpose        object
Application_Date         object
Product_ID               object
dtype: object


insurance_products
Product_ID      object
Product_Name    object
dtype: object

#### From observation some date cols have been stored as object types. We need to correct this before exporting to BigQuery

In [ ]:
# Convert date cols to date dtypes (date only)
date_cols = [
    "Policy_Start_Date",
    "Policy_End_Date",
    "Payment_Date",
    "Premium_Date",
    "Claim_Date",
    "Payout_Date",
    "Application_Date",
    "Submitted_Date",
    "Reviewed_Date"
]

for key, value in tables.items():
  for col in date_cols:
    if col in value.columns:
      # Convert to datetime first, then extract the date component
      value[col] = pd.to_datetime(value[col]).dt.date

In [ ]:
# Check dtypes again
for key, value in tables.items():
  print(key)
  print(value.dtypes)
  print('\n')

companies
ID              object
Company_Name    object
Industry        object
dtype: object


branches
Branch_ID          object
Region             object
Number_of_Staff     int64
Corporate_ID       object
dtype: object


covered_employees
Employee_ID           object
Branch_ID             object
Employee_Name         object
Occupation            object
Grade_Level           object
Monthly_Salary_GHS     int64
Age                    int64
Gender                object
Dependents             int64
Smoker                object
dtype: object


claims
Claim_ID            object
Employee_ID         object
Claim_Type          object
Claim_Amount_GHS     int64
Claim_Status        object
Claim_Date          object
dtype: object


premium_payments
Payment_ID        object
Branch_ID         object
Payment_Date      object
Amount_GHS         int64
Payment_Status    object
Payment_Method    object
dtype: object


claim_workflow
Workflow_ID       object
Claim_ID          object
Submitted_Date    object
Reviewed_Date     object
Approved_By       object
Payout_Date       object
dtype: object


beneficiaries
Beneficiary_ID           object
Employee_ID              object
Beneficiary_Name         object
Relationship             object
Allocation_Percentage     int64
dtype: object


policy_table
Policy_ID            object
Branch_ID            object
Product_ID           object
Policy_Start_Date    object
Policy_End_Date      object
Policy_Status        object
dtype: object


customers_info
Customer_ID            object
Full_Name              object
Age                     int64
Gender                 object
Occupation             object
Grade_Level            object
Monthly_Income_GHS      int64
Region                 object
Smoker                 object
BMI                   float64
Marital_Status         object
Dependents              int64
dtype: object


customer_policies
Customer_ID          object
Product_ID           object
Agent_ID             object
Premium_GHS         float64
Payment_Method       object
Application_Date     object
Policy_Status        object
Tenure_Months         int64
Payment_Behavior     object
Claim_Frequency       int64
Claim_Severity       object
dtype: object


agents
Agent_ID      object
Agent_Name    object
dtype: object


corporate_insurance
Insurance_ID             object
Branch_ID                object
Premium_Per_Staff_GHS     int64
Insurance_Purpose        object
Application_Date         object
Product_ID               object
dtype: object


insurance_products
Product_ID      object
Product_Name    object
dtype: object

In [ ]:
from datetime import date
# Export data to BigQuery
import os
from google.cloud import bigquery

# Set up credentials
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = r"/content/drive/MyDrive/Datasets/alx-data-community-498121-464a202ca657.json"


def load_dfs_to_BigQuery(tables, project_id, dataset_id):
    client = bigquery.Client(project=project_id)

    # Configure the job to truncate (overwrite) the table
    job_config = bigquery.LoadJobConfig(
        write_disposition=bigquery.WriteDisposition.WRITE_TRUNCATE
    )

    for table_name, df in tables.items():
        table_ref = f"{project_id}.{dataset_id}.{table_name}"

        job = client.load_table_from_dataframe(df, table_ref, job_config=job_config)
        job.result()  # Wait for the load to finish

In [ ]:
# Export the data into BigQuery

load_dfs_to_BigQuery(tables=tables,
                     project_id='alx-data-community-498121',
                     dataset_id='insurance_dataset')

In [ ]:
# check tables shape
companies.shape

(7, 3)

In [ ]:
# check tables shape
branches.shape

(70, 4)

In [ ]:
# check tables shape
beneficiaries.shape

(1974, 5)

In [ ]:
# check tables shape
claims.shape

(2500, 6)

In [ ]:
# check tables shape
covered_employees.shape

(1974, 10)

In [ ]:
# check tables shape
claim_workflow.shape

(165, 6)

In [ ]:
# check table shape
corporate_insurance.shape

(70, 6)

In [ ]:
# check table shape
premium_payments.shape

(420, 6)